### ISSUE TITLE
Docs for useScrambledText hook incorrect

### ISSUE THREAD

**Issue by madeleineostoja** [good-idea/scrambled-text#20]
The README says that `useScrambledText` takes 2 arguments, but it actually takes 1 with `text` as a property in the config object. Only figured it out thanks to typescript

**Comment by good-idea** [comment]
Hi @madeleineostoja , thanks for opening this issue, and sorry it took me so long to see it! I've updated the API of `useScrambledText`. It has changed a little bit in `1.4.0`, you can see the changes in the updated readme. (apologies if this breaking change breaks something on your end! You're perhaps one of the few people other than me who has used this lib :P )
